### ISSUE TITLE
Raster Export — no emails or confirmation?

### ISSUE THREAD

**Issue by livinglands** [bcgov/HectaresBC#10]
Hi, I'd like to download many raster layers on climate. I sent a number of exports to the queue but have not received email confirmation? 

I have another data related question, but will make a separate "issue" to keep things tidy!

Thanks!

**Comment by egouge** [comment]
I just sent you an email with links to the downloads - let me know if you don't get it.

**Comment by livinglands** [comment]
Wow, thanks Emily, that was super fast!

Did you see my post about getting the full climate data sets?

Super appreciated!

Andrew
