### ISSUE TITLE
Download complete datasets?

### ISSUE THREAD

**Issue by livinglands** [bcgov/HectaresBC#11]
Hi,

I'd like to download all the layers in the following datasets:
1) Climate Normals 1961-1990
2) Climate Most Recent Decade
3) Climate Future 2050 (RCP85)
4) Climate Future 2080 (RCP80)

Thank you, it would be fantastic if this could be set up. I can do it in small batches, however, it works for your server. Happy to click-and-come-again!

**Comment by egouge** [comment]
I think it's probably easiest if I can compile them for you - let me try to compile them.

**Comment by livinglands** [comment]
Wow, that would be super! I know it’s a pile of megabytes...

**Comment by egouge** [comment]
I've send some links for you.
