### ISSUE TITLE
Looking for a link to my batch queue results

### ISSUE THREAD

**Issue by Samiam2185** [bcgov/HectaresBC#12]
Hello! The terms and conditions said I should submit an issue here to receive the data I requested.

I'm looking for raster data of the Mean Annual Precipitation (Climate Normals), M.A.P. (Climate Futures 2080 RCP45), and M.A.P. (Climate Futures 2080 RCP85). I have added the request to the Batch Queue and its current status is "queued". 

Thanks for the help!

Sam

**Comment by egouge** [comment]
You should have an email in your inbox with the link to the exports.  Let me know if if you didn't get it.

**Comment by Samiam2185** [comment]
Got it! Thank you very much.
