### ISSUE TITLE
Batch Queue email request

### ISSUE THREAD

**Issue by PaperCorvid** [bcgov/HectaresBC#14]
I have submitted the following request for batch queue results:
Elevation : Topography & Mean
Annual Precipitation
and was told by the notification in your terms and conditions to follow up here to get the request processed

**Comment by egouge** [comment]
what email address did you use to submit to the batch queue (or just provide me with part of it) - thanks?

**Comment by PaperCorvid** [comment]
Hello Emily,

Thanks for your quick response. I provided this email (
***@***.***) when requesting the data

**Comment by egouge** [comment]
ha - it looks like github removes emails from messages.  Can you just email me: e g o u g e @ r e f r a c t i o n s . n e t  and we can take it from there.
