### ISSUE TITLE
Links do not lead to download

### ISSUE THREAD

**Issue by gjherm** [bcgov/HectaresBC#22]
Hi! I have received the link for my datasets and when I open it, no download is started. Just wondering if others have experienced this issue and how I could fix it.

Thanks!

**Comment by egouge** [comment]
"The batch queue email notification system is currently not working. If you require batch queue results, add the tasks to the batch queue then submit an issue here. We will follow-up on issues and provide links to the results."

Did you actually get an email with the link?  Last time I checked it wasn't working.  

I'll have a look at the batch queue and send you a link to your results now.

**Comment by egouge** [comment]
The downloads were actually being blocked for malware.
