### ISSUE TITLE
Trying to download the 12 rasters in VRI/Species - All

### ISSUE THREAD

**Issue by LionelLeston** [bcgov/HectaresBC#4]
Hi. A colleague of mine named Melina Houle tipped me off to your website yesterday. I am trying to develop VRI-based B.C. bird species abundance models using the high-resolution environmental data stored on your website. I am interested in the 12 rasters for the 6 most common leading tree species and their percent covers in each grid cell, because tree species type and abundance are used by both foresters and ecologists to predict how many birds are at risk of incidental take from logging in the breeding season. I've tried 3 times to download the Species-All layers and received an error each time. I'm not sure if it's because I'm trying to downloaded 12 layers in one order. I had a similar problem before when I tried downloading 3 layers at once in the same order, but was able to get single layers downloaded one at a time.

**Comment by egouge** [comment]
There were some permission issues with the database.  I believe I've fixed these.  I was able to export the "Species-All Layers" dataset from the Raster Data Tab.  Can you try again and let me know if it works (it does take some time to finish processing).  Thanks.

**Comment by LionelLeston** [comment]
Hi Emily,
I just sent the request again now. I see what you mean about a longer
processing time:)
Thanks again for your help!
Lionel

**Comment by LionelLeston** [comment]
I've downloaded Species__All and I'm able to open the raster map in R. I have a question about the metadata though. I see that there are multiple raster values assigned to the same species or species-groups, which I assume is because the same leading species might be determined from different percent covers of the up-to-6 most common species in each grid cell. I'm interested in knowing if there are individual raster layers for the identities and percent covers of species 1 through 6 in each grid cell, like the columns in the original VRI. The reason for this is that foresters and some bird ecologists are interested in comparing bird abundance in relatively pure stands of a tree species vs. stands where there is more of a mix of species. For example in BC, at least one bird biologist that I know has hypothesized that coniferous stands containing some minimum amount of deciduous trees should have more birds than pure stands of a single conifer species. 

If rasterized layers of the identities and percent covers of species 1 thru 6 aren't available through Hectares BC, another possibility could be to know exactly what different raster values that are coded to the same species stand for. For example, raster values 1 through 6 are classified as Aspen-Cottonwood but I'm assuming that each raster value is from a different set of percent cover values in which it was decided that the grid cell was best classed as Aspen-Cottonwood. Maybe raster value=1 refers to pure stands, raster value=2 refers to >50% Aspen-Cottonwood, raster value=3 refers to Aspen-Cottonwood<50 % but is more abundant than next most common tree (pine), raster value=4 refers to Aspen-Cottonwood<50 % but is more abundant than next most common tree (balsam fir), etc. If I know what rough tree combinations are associated with each raster value, then I can come up with a ruleset for reclassifying some grid cells for my own work, e.g. some Yellow Pine becomes Yellow Pine-D (for deciduous).  

A third option, less preferred, is for me to use a Deciduous % cover satellite layer to overlay over the species_all layer and serve as a modifier.

**Comment by LionelLeston** [comment]
One last thing: in the metadata, the bottom-most raster grid cell value in the Excel spreadsheet has no associated tree species assignment. I'm treating it as Unknown for now but wanted to confirm.

**Comment by egouge** [comment]
At this time the raster layers for the percent species covers 2 thru 6 do not exist.  Species cover 1 is represented by the layer "Species - Lead" 

The "Species - All" layer is computed by "randomly" selecting one of the 6 species based on there percentages.  So a hectare which is 75% Pine and 25% Cedar has a 25% chance of being flagged as Cedar and 75% chance of being flagged as Pine.  But it's random as to which one is selected.

The individual values represent different sub tree species.  For example Aspen-Cottonwood represents raster values 1 thru 6, but 1 might be "poplar  P. balsamifera  Ac" and 2 might be " balsam poplar  P. b. ssp. balsamifera  Acb".  I don't know what the actual values are.

If we do a data refresh fro VRI it may be possible to add raster for Species Covers 2 thru 6 but that will need to be brought up with the HaBC administrators.

A metadata value of 97 (the last row) means NULL/None in this case (there are no values for any of the species code).

**Comment by LionelLeston** [comment]
Thanks!

**Comment by LionelLeston** [comment]
"The "Species - All" layer is computed by "randomly" selecting one of the 6 species based on there percentages. So a hectare which is 75% Pine and 25% Cedar has a 25% chance of being flagged as Cedar and 75% chance of being flagged as Pine. But it's random as to which one is selected."

_I'm assuming you have a 1-ha kernel or moving window. If percent cover or tree species identification for SP1 through 6 is missing, the tree species is classes as Unknown or do you have some kind of K Nearest Neighbours technique where you look beyond each hectare for a certain distance to reduce the number of Unknown classifications?

Depending on whether my colleagues are open to this, I might reclassify some stands as mixtures in my work by creating binary rasters for each species from the Species_all layer or Species_lead layer, generating a buffer around my points, and calculating proportions of each species within a certain distance of point counts._

The individual values represent different sub tree species. For example Aspen-Cottonwood represents raster values 1 thru 6, but 1 might be "poplar P. balsamifera Ac" and 2 might be " balsam poplar P. b. ssp. balsamifera Acb". I don't know what the actual values are.

_I would be interested in these sub-classifications since for example bird communities could be different between aspen and cottonwood forests._

**Comment by egouge** [comment]
We first rasterized the dataset, so each raster cell was associated with one of the polygons in the vector dataset.  I believe we did this by using the center point of the raster cell (I can confirm if this is really important).  Once rasterzied we used the species values/percents associated with the polygon of the hectare.

I am not sure we still have the mappings to the subspecies, but I will have a look and see if I can find it.

**Comment by egouge** [comment]
I think this is the complete mapping for species:

```
 species | habc_id
---------+---------
 AC      |       1
 ACB     |       2
 ACT     |       3
 AD      |       4
 AT      |       5
 AX      |       6
 B       |       7
 BA      |       8
 BB      |       9
 BG      |      10
 BL      |      11
 BM      |      12
 BP      |      13
 C       |      14
 CW      |      15
 D       |      16
 DG      |      17
 DM      |      18
 DR      |      19
 E       |      20
 EA      |      21
 EB      |      22
 EE      |      23
 EP      |      24
 ES      |      25
 EW      |      26
 EXP     |      27
 F       |      28
 FD      |      29
 FDC     |      30
 FDI     |      31
 G       |      32
 GP      |      33
 H       |      34
 HM      |      35
 HW      |      36
 HX      |      37
 HXM     |      38
 JR      |      39
 L       |      40
 LA      |      41
 LS      |      42
 LT      |      43
 LW      |      44
 M       |      45
 MB      |      46
 MV      |      47
 OA      |      48
 P       |      49
 PA      |      50
 PF      |      51
 PJ      |      52
 PL      |      53
 PLC     |      54
 PLI     |      55
 PM      |      56
 PR      |      57
 PW      |      58
 PY      |      59
 Q       |      60
 QG      |      61
 RA      |      62
 S       |      63
 SA      |      64
 SB      |      65
 SE      |      66
 SN      |      67
 SS      |      68
 SW      |      69
 SX      |      70
 SXB     |      71
 SXE     |      72
 SXL     |      73
 SXS     |      74
 SXW     |      75
 T       |      76
 TW      |      77
 U       |      78
 V       |      79
 VB      |      80
 VP      |      81
 W       |      82
 WA      |      83
 WB      |      84
 WD      |      85
 WP      |      86
 WS      |      87
 WT      |      88
 X       |      89
 XC      |      90
 XH      |      91
 Y       |      92
 YC      |      93
 Z       |      94
 ZC      |      95
 ZH      |      96
         |      97

```

**Comment by LionelLeston** [comment]
Thanks!
