### ISSUE TITLE
VRI Height raster

### ISSUE THREAD

**Issue by LionelLeston** [bcgov/HectaresBC#5]
What is the unit for height in the VRI raster for leading tree height? In the legend on the website, it looks like it would be in meters. When I examine the raster in R, maximum values are much higher, up to 600 and most are > 100. Are the height units in 1-cm or 10-cm increments?

**Comment by egouge** [comment]
The raster file (downloaded from the Raster Data tab) has a scale factor of 0.1 applied to all the data (from the height.metadata.html file):
`<meta name="scale_factor" content="0.1"></meta>`

So units are 10cm increments - ie a raster value of 600 = 60.0 m

**Comment by LionelLeston** [comment]
Thanks! That's what I thought!

**Comment by LionelLeston** [comment]
Thanks! I've closed the issue on the Github site and will watch for scale
factors indicated in the metadata in the future.

Lionel
