### ISSUE TITLE
Not receiving batch queue results

### ISSUE THREAD

**Issue by TRVil** [bcgov/HectaresBC#7]
Hello,

I tried to download some raster layers but never received the results in my email. In the My HaBC tab it says they are all done. In the page where you agree to the terms and conditions it says the batch queue is not working and to place the issue here.

Thank-you very much for you help!

**Comment by egouge** [comment]
I emailed you links to the files.

**Comment by TRVil** [comment]
Hi Emily,

Thank-you so much, that was very quick!
Talia

**Comment by TRVil** [comment]
Hi Emily,

I was just wondering if a layer symbology file is available for these files? If not its not a problem – their symbology is pretty straight forwards to categorize.

Thank-you!
Taila

**Comment by egouge** [comment]
Not easily - our mapfile contains all styling for all layers in hectares and is not easily useable.  What I can do is provide you with the xml file used to generate this map file for these layers - these xml files contain the raster values and associated colors used.  
[metadata_classes.zip](https://github.com/bcgov/HectaresBC/files/5645680/metadata_classes.zip)

**Comment by TRVil** [comment]
Thank you!
Talia
